# Generated by Django 5.1.1 on 2024-12-01 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_customuser_groups_customuser_user_permissions'),
        ('search_app', '0003_product_createuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='favorite_place',
            field=models.ManyToManyField(blank=True, to='search_app.product'),
        ),
    ]
